// benchmark/size/vue/components/App/index.vue
<template>
    <div>
        <h1>
            Hello {{name}}!
        </h1>

        <div class="colors">
            <ul v-if="colors.length">
                <li v-for="color in colors" class="color" v-bind:style="'background-color: ' + color">
                    {{color}}
                </li>
            </ul>
            <div v-else>
                No colors!
            </div>
        </div>
        <button type="button" v-on:click="clickCount += 1">
            You clicked the button {{clickCount}} time(s)
        </button>
    </div>
</template>

<script>
module.exports = {
    data() {
        return {
            clickCount: 0,
            name: 'Frank',
            colors: ['red', 'green', 'blue']
        }
    },
    methods: {
        handleButtonClick: function() {
            this.clickCount++;
        }
    }
}
</script>

// benchmark/size/inferno/components/App/index.jsx
'use strict';
import Inferno from 'inferno';
import Component from 'inferno-component';

function renderColor(color) {
    var style = {
        backgroundColor: color
    };

    return <li className="color" style={style}>
            {color}
        </li>
}

function renderColors(colors) {
    if (colors.length) {
        return (<ul>{colors.map(renderColor)}</ul>);
    } else {
        return <div>No colors!</div>
    }
}

export default class extends Component {
    constructor(props) {
        super(props);
        this.state = {
            name: props.name,
            colors: props.colors,
            clickCount: 0
        }

        this.handleButtonClick = function() {
            this.setState({
                clickCount: this.state.clickCount + 1
            });
        }.bind(this);
    }

    render() {
        var colors = this.state.colors;
        var name = this.state.name;
        var clickCount = this.state.clickCount;
        var handleButtonClick = this.handleButtonClick;

        return (
            <div>
                <h1>Hello {name}!</h1>
                <div className="colors">
                    {renderColors(colors)}
                </div>
                <button type="button" onClick={handleButtonClick}>
                    You clicked the button {clickCount} time(s)
                </button>
            </div>
        );
    }
};
